---
- set_fact:
    repo_url: https://dl.yarnpkg.com/rpm/yarn.repo

- name: "Add Yarn repository"
  shell: "yum-config-manager --add-repo={{ repo_url }}"
  args:
    creates: /etc/yum.repos.d/yarn.repo

- name: "Install Yarn"
  yum:
    state: present
    name: "yarn"

- name: "Check it works"
  shell: yarn -v
