---
- hosts: localhost
  become: true
  tasks:
    - name: "Update system"
      yum:
        name: '*'
        state: latest

    - name: "Create security group"
      ec2_group:
        name: "student_machines"
        description: "Allow SSH connections"
        vpc_id: "vpc-aaad94d0"
        region: us-east-1
        rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow ssh

    - name: "Create machines"
      ec2:
        region: us-east-1
        group: student_machines
        key_name: bastillion
        instance_type: t2.micro
        instance_profile_name: test-student
        wait: true
        wait_timeout: 500
        count: 1
        instance_tags:
            student: "stud-{{ item }}"
            Name: "Bation-{{ item }}"
        image: ami-0fc61db8544a617ed
      with_sequence: start=1 end=18
